apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: adarshanatia/trello_backend:9268d8836efe0385f42fb5f8c59042ac04d499c4
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: trello-secrets
          env:
            - name: BACKEND_PORT
              value: "3000"
            - name: PROD
              value: "true"
            - name: FRONTEND_URL
              value: "https://trello.adarshanatia.xyz"
            - name: BACKEND_URL
              value: "https://trello.adarshanatia.xyz"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
