apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
        - name: websocket
          image: adarshanatia/trello_websocket:145c5fd2bef5af029e5f0fc430e5c7d54abbd92d
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-svc
spec:
  selector:
    app: websocket
  ports:
    - port: 8080
      targetPort: 8080
