apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
        - name: websocket
          image: adarshanatia/trello_websocket:c5a320d215b2a75ffd58f51de18708e42fd8860e
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-svc
spec:
  selector:
    app: websocket
  ports:
    - port: 8080
      targetPort: 8080
