apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
        - name: websocket
          image: adarshanatia/trello_websocket:9522f4353025f6a40a61e71f976e3640bff5dfc8
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-svc
spec:
  selector:
    app: websocket
  ports:
    - port: 8080
      targetPort: 8080
