import { Router } from "express";
import { isPrismaErrorCode, prisma } from "@repo/db/client";
import { generateKeyBetween } from "fractional-indexing";
import { requireAuth } from "../auth_middleware";

const router = Router();
router.use(requireAuth);

// Fractional order keys generated by `fractional-indexing` are ASCII
// alphanumeric, e.g. "a0", "a0V", "b00". Anything outside that shape is
// rejected before it can pollute column ordering.
const ORDER_KEY_RE = /^[0-9A-Za-z]{1,64}$/;

// Control-flow error so route handlers can abort with a status cleanly.
class RouteError extends Error {
  constructor(
    public status: number,
    message: string,
  ) {
    super(message);
  }
}

async function canAccessBoard(userId: string | undefined, boardId: string) {
  const board = await prisma.board.findUnique({ where: { id: boardId } });
  if (!board) return null;
  const m = await prisma.membership.findUnique({
    where: { userId_orgId: { userId: userId!, orgId: board.orgId } },
  });
  return m?.accepted ? board : null;
}

router.get("/issues", async (req, res) => {
  const { boardId } = req.query;
  if (!(await canAccessBoard(req.userId, boardId as string))) {
    res.status(403).json({ error: "Not a member of this organization" });
    return;
  }
  const issues = await prisma.issue.findMany({
    where: { boardId: boardId as string },
    orderBy: { position: "asc" },
  });
  const groupedbySection = Object.groupBy(issues, (issues) => issues.sectionId);

  res.json(groupedbySection);
});

router.get("/issue/:issueId", async (req, res) => {
  // Light fetch for the owning board, then authorize, then load the full
  // detail (users + comments) only for members.
  const existing = await prisma.issue.findUnique({
    where: { id: req.params.issueId },
    select: { boardId: true },
  });
  if (!existing || !(await canAccessBoard(req.userId, existing.boardId))) {
    res.status(404).json({ error: "Issue not found" });
    return;
  }
  const issue = await prisma.issue.findUnique({
    where: { id: req.params.issueId },
    include: {
      users: {
        include: { user: { select: { id: true, name: true, email: true } } },
      },
      comments: {
        include: { user: { select: { id: true, name: true } } },
        orderBy: { createdAt: "asc" },
      },
    },
  });
  if (!issue) {
    res.status(404).json({ error: "Issue not found" });
    return;
  }
  res.json(issue);
});

router.post("/issue", async (req, res) => {
  const { title, description, sectionId, boardId } = req.body;
  if (!(await canAccessBoard(req.userId, boardId))) {
    res.status(403).json({ error: "Not a member of this organization" });
    return;
  }
  const section = await prisma.section.findUnique({ where: { id: sectionId } });
  if (!section || section.boardId !== boardId) {
    res.status(404).json({ error: "Section not found" });
    return;
  }

  // Single-row insert — atomic on its own, no transaction needed. Two
  // creates in the same column at the same instant can compute the same
  // key; the unique (sectionId, position) index rejects the loser with a
  // 409 instead of corrupting order.
  const last = await prisma.issue.findFirst({
    where: { sectionId },
    orderBy: { position: "desc" },
  });
  try {
    res.status(201).json(
      await prisma.issue.create({
        data: {
          title,
          description,
          boardId,
          sectionId,
          position: generateKeyBetween(last?.position ?? null, null),
        },
      }),
    );
  } catch (e) {
    if (isPrismaErrorCode(e, "P2002")) {
      res.status(409).json({ error: "Position conflict, please retry" });
      return;
    }
    if (isPrismaErrorCode(e, "P2003")) {
      // Section deleted between the check above and this insert.
      res.status(404).json({ error: "Section not found" });
      return;
    }
    throw e;
  }
});

router.put("/issue", async (req, res) => {
  const { issueId, title, description } = req.body;
  const existing = await prisma.issue.findUnique({
    where: { id: issueId },
    select: { boardId: true },
  });
  if (!existing || !(await canAccessBoard(req.userId, existing.boardId))) {
    res.status(404).json({ error: "Issue not found" });
    return;
  }
  res.json(
    await prisma.issue.update({
      where: { id: issueId },
      data: {
        ...(title !== undefined && { title }),
        ...(description !== undefined && { description }),
      },
    }),
  );
});

// Fractional indexing: the client computes a key that sorts between the
// card's new neighbors and sends it. Reordering touches exactly one row —
// atomic on its own, no transaction needed. The unique
// (sectionId, position) index is the guard against concurrent moves.
router.put("/issue/move", async (req, res) => {
  const { issueId, targetSectionId, newKey } = req.body;
  if (typeof newKey !== "string" || !ORDER_KEY_RE.test(newKey)) {
    res.status(400).json({ error: "Invalid position key" });
    return;
  }

  const issue = await prisma.issue.findUnique({ where: { id: issueId } });
  if (!issue || !(await canAccessBoard(req.userId, issue.boardId))) {
    res.status(404).json({ error: "Issue not found" });
    return;
  }
  const section = await prisma.section.findUnique({
    where: { id: targetSectionId },
  });
  if (!section || section.boardId !== issue.boardId) {
    res.status(404).json({ error: "Target section not found" });
    return;
  }

  try {
    res.json(
      await prisma.issue.update({
        where: { id: issueId },
        data: { sectionId: targetSectionId, position: newKey },
      }),
    );
  } catch (e) {
    if (isPrismaErrorCode(e, "P2002")) {
      // Another client concurrently placed a card on the same key.
      // Their board refetches and converges on server truth.
      res.status(409).json({ error: "Position conflict, board will resync" });
      return;
    }
    if (isPrismaErrorCode(e, "P2002") || isPrismaErrorCode(e, "P2025")) {
      // Issue or section vanished between the checks above and the write.
      res.status(404).json({ error: "Issue not found" });
      return;
    }
    throw e;
  }
});

router.delete("/issue", async (req, res) => {
  const { issueId } = req.body;
  const issue = await prisma.issue.findUnique({ where: { id: issueId } });
  if (!issue || !(await canAccessBoard(req.userId, issue.boardId))) {
    res.status(404).json({ error: "Issue not found" });
    return;
  }
  // No sibling repositioning needed: fractional keys stay sparse and
  // ordered after a removal.
  await prisma.issue.delete({ where: { id: issueId } });
  res.status(204).send();
});

export default router;
